export default {
	USER_SESSION: 'userSession',
	MAX_CHART_RESULTS: 6,
	INITIATED: 'INICIADO',
	COMPLETED_WITH_OBSERVATIONS: 'COMPLETADO CON OBSERVACIONES',
	COMPLETED: 'COMPLETADO',
	NOT_COMPLETED: 'NO COMPLETADO',
	COMPLETED_WITH_ERRORS: 'COMPLETADO CON ERRORES',
	DISRUPTED: 'INTERRUMPIDO',
	START: 'INICIO',
}
